### ISSUE TITLE
Implement group command

### ISSUE THREAD

**Issue by mcurlej** [rpm-software-management/dnf5#138]
**Command:** ```group```
**Aliases:** ```grp```
**Deprecated aliases:** ```groups```, ```grouplist```, ```groupinstall```, ```groupupdate```, ```groupremove```, ```grouperase```, ```groupinfo```

Groups are virtual collections of packages. DNF keeps track of groups that the user selected (“marked”) installed and can manipulate the comprising packages with simple commands.

- [ ] ```dnf [options] group [summary] <group-spec>```

Display overview of how many groups are installed and available. With a spec, limit the output to the matching groups. summary is the default groups subcommand.

- [x] ```dnf [options] group info <group-spec>```

Display package lists of a group. Shows which packages are installed or available from a repository when ```-v``` is used.

- [x] ```dnf [options] group install [--with-optional] <group-spec>...```

Mark the specified group installed and install packages it contains. Also include optional packages of the group if ```--with-optional``` is specified. All mandatory and Default packages will be installed whenever possible. Conditional packages are installed if they meet their requirement. If the group is already (partially) installed, the command installs the missing packages from the group. Depending on the value of [obsoletes configuration option](https://dnf.readthedocs.io/en/latest/conf_ref.html#obsoletes-conf-option-label) group installation takes obsoletes into account.

- [x] ```dnf [options] group list <group-spec>...```

List all matching groups, either among installed or available groups. If nothing is specified, list all known groups. ```--installed``` and ```--available``` options narrow down the requested list. Records are ordered by the display_order tag defined in comps.xml file. Provides a list of all hidden groups by using option ```--hidden```. Provides group IDs when the ```-v``` or ```--ids``` options are used.

- [x] ```dnf [options] group remove <group-spec>...```

Mark the group removed and remove those packages in the group from the system which do not belong to another installed group and were not installed explicitly by the user.

- [x] ```dnf [options] group upgrade <group-spec>...```

Upgrades the packages from the group and upgrades the group itself. The latter comprises of installing packages that were added to the group by the distribution and removing packages that got removed from the group as far as they were not installed explicitly by the user.

Groups can also be marked installed or removed without physically manipulating any packages:

- [x] ```dnf [options] group mark install <group-spec>...```

Mark the specified group installed. No packages will be installed by this command, but the group is then considered installed.

- [x] ```dnf [options] group mark remove <group-spec>...```

Mark the specified group removed. No packages will be removed by this command.

**Comment by glum23** [comment]
What is the exact plan with the deprecated aliases? E.g. 'dnf5 grouplist' works while 'dnf5 groupinstall <group>' does not work. It'd be nice when the availability of the aliases is consistent.

**Comment by evan-goode** [comment]
Moving this back to Todo since some items are still incomplete.

**Comment by ilikelinux69** [comment]
I found an error that while try to use the `dnf group install` command , groups with capital first letters will not be included.
[While testing](https://docs.fedoraproject.org/en-US/quick-docs/installing-plugins-for-playing-movies-and-music/) 
and I simply get the error: `No match for argument: Multimedia`

While reading how dnf5 group now works, makes sense for me, to exclude capital letters while package names not use them, right?

I'm trying to catch up such kind of errors, because Fedora 41 will release DNF5 by default, and we do have documentations where we use the group names with capital first letters (dnf4). I reported this issue also in discussion.fedoraproject.org if someone would like to participate on a that discussion:

https://discussion.fedoraproject.org/t/dnf5-is-not-ignoring-case-distinctions-while-working-with-groups/130530

**Comment by jan-kolarik** [comment]
> I found an error that while try to use the `dnf group install` command , groups with capital first letters will not be included. [While testing](https://docs.fedoraproject.org/en-US/quick-docs/installing-plugins-for-playing-movies-and-music/) commands in the documentation I simply get the error: `No match for argument: Multimedia`
> 
> While reading how dnf5 group now works, makes sense for me, to exclude capital letters while package names not use them, right?
> 
> I'm trying to catch up such kind of errors, because Fedora 41 will release DNF5 by default, and we do have documentations where we use the group names with capital first letters (dnf4). I reported this issue also in discussion.fedoraproject.org if someone would like to participate on a that discussion:
> 
> https://discussion.fedoraproject.org/t/dnf5-is-not-ignoring-case-distinctions-while-working-with-groups/130530

I think the answer why it's like that is here: https://github.com/rpm-software-management/dnf5/issues/1666.

**Comment by ilikelinux69** [comment]
I saw it now, an it makes sense that we should keep just using the ID for group installation. And also removing the aliases makes sense, to have one syntax for installation with dnf group. Thx for the answer/link.

**Comment by pkratoch** [comment]
The `group mark install/remove` has been documented as dropped: https://github.com/rpm-software-management/dnf5/commit/71e70faa5ea4f30c3e9ac7a78f32f0548d5a2b9a#diff-ff83c5037d25bcd5859dae54e80afc07f9b24cf4eae8cb990eba69b0c6e3dbcfR188
Therefore, I am checking the two boxes for the `mark` subcommand.

**Comment by fhbash** [comment]
After the dev team meeting, we decide it's not make sense we have `dnf [options] group [summary] <group-spec>` on dnf5. Closing this issue, since all other items was already done/closed.

**Comment by beedell-roke** [comment]
@fhbash, how should one manage groups, in its stead?

**Comment by evan-goode** [comment]
We're only dropping the `group summary` subcommand. `dnf5 group list --available`, `dnf5 group list --installed`, and `dnf5 group info <group name>` can do anything `dnf4 group summary` could.
