### ISSUE TITLE
Implement provides command

### ISSUE THREAD

**Issue by mcurlej** [rpm-software-management/dnf5#147]
- [x] **Command:** ```provides```
  - Priority medium 

- [x] **Aliases:** ```prov```, ```whatprovides```, ```wp```
  - To many aliases - proposing to keep `whatprovides` or no aliases at all
  - Priority low

- [x] ```dnf [options] provides <provide-spec>```

Finds the packages providing the given ```<provide-spec>```. This is useful when one knows a filename and wants to find what package (installed or not) provides this file. The ```<provide-spec>``` is gradually looked for at following locations:

- [x] 1. The ```<provide-spec>``` is matched with all file provides of any available package:

```

- [ ] $ dnf provides /usr/bin/gzip

gzip-1.9-9.fc29.x86_64 : The GNU data compression program
Matched from:
Filename    : /usr/bin/gzip
```

2. Then all provides of all available packages are searched:

```
$ dnf provides "gzip(x86-64)"
gzip-1.9-9.fc29.x86_64 : The GNU data compression program
Matched from:
Provide     : gzip(x86-64) = 1.9-9.fc29
```

3. DNF assumes that the ```<provide-spec>``` is a system command, prepends it with ```/usr/bin/```, ```/usr/sbin/``` prefixes (one at a time) and does the file provides search again. For legacy reasons (packages that didn’t do UsrMove) also /bin and /sbin prefixes are being searched:

- [ ] $ dnf provides zless
```
gzip-1.9-9.fc29.x86_64 : The GNU data compression program
Matched from:
Filename    : /usr/bin/zless
```

4. If this last step also fails, DNF returns “Error: No Matches found”.

This command by default does not force a sync of expired metadata. See also [Metadata Synchronization](https://dnf.readthedocs.io/en/latest/command_ref.html#metadata-synchronization-label).

**Comment by glum23** [comment]
dnf commands provides/whatprovides together with options --provides/--whatprovides are pretty confusing. It'd be nice to reduce this confusion in dnf5. How about marking "provides" command as obsoleted (without any aliases) and suggest to use the options instead?

**Comment by modzilla99** [comment]
> dnf commands provides/whatprovides together with options --provides/--whatprovides are pretty confusing. It'd be nice to reduce this confusion in dnf5. How about marking "provides" command as obsoleted (without any aliases) and suggest to use the options instead?

I understand what you mean. But I'm in favor of keeping at least the "provides" subcommand. I don't use "whatprovides" or any of the flags. I think there are already to many flags and using a subcommand is much easier to learn as I know some that use "provide" as well. It's also nice for tab completion.

**Comment by inknos** [comment]
@glum23 
a note:
`dnf provides` gives a bit more context than `dnf repoquery --whatprovides`

```
$ dnf repoquery --whatprovides bash
bash-0:5.1.16-4.fc37.x86_64
bash-0:5.2.15-1.fc37.i686
bash-0:5.2.15-1.fc37.x86_64
```

```
$ dnf provides bash
Last metadata expiration check: 0:00:40 ago on Út 18. dubna 2023, 12:01:24.
bash-5.1.16-4.fc37.x86_64 : The GNU Bourne Again shell
Repo        : fedora
Matched from:
Provide    : bash = 5.1.16-4.fc37

bash-5.2.15-1.fc37.i686 : The GNU Bourne Again shell
Repo        : updates
Matched from:
Provide    : bash = 5.2.15-1.fc37

bash-5.2.15-1.fc37.x86_64 : The GNU Bourne Again shell
Repo        : @System
Matched from:
Provide    : bash = 5.2.15-1.fc37

bash-5.2.15-1.fc37.x86_64 : The GNU Bourne Again shell
Repo        : updates
Matched from:
Provide    : bash = 5.2.15-1.fc37
```
`provides` also highlights matching Provide **or** File and so it carries more information than `--whatprovides`

**Comment by inknos** [comment]
The command is implemented.

No alias were implemented.

I would like to `dnf provides "gzip(x86-64)"` is documented but actually does not work (tested on fedora:latest container). Should we remove that piece of documentation?
```
[root@77f6b5af11a0 /]# dnf provides -q "gzip(x86-64)"
Error: No matches found. If searching for a file, try specifying the full path or using a wildcard prefix ("*/") at the beginning.
```

**Comment by j-mracek** [comment]
With DNF4 it works:

```
dnf provides "gzip(x86-64)"
Last metadata expiration check: 0:10:37 ago on Wed 06 Dec 2023 09:44:00 AM CET.
gzip-1.12-3.fc38.x86_64 : GNU data compression program
Repo        : @System
Matched from:
Provide    : gzip(x86-64) = 1.12-3.fc38

gzip-1.12-3.fc38.x86_64 : GNU data compression program
Repo        : fedora
Matched from:
Provide    : gzip(x86-64) = 1.12-3.fc38
```

**Comment by inknos** [comment]
something must be wrong on my side then

**Comment by m-blaha** [comment]
> something must be wrong on my side then

Doesn't your laptop use a different architecture?

**Comment by inknos** [comment]
> Doesn't your laptop use a different architecture?

it does, I tried it on aarch too

**Comment by j-mracek** [comment]
`dnf provides "gzip(x86-64)" --forcearch='x86_64'` should help or try `dnf provides "gzip(aarch-64)"` for `aarch64`

**Comment by jan-kolarik** [comment]
I am closing this as all `provides` functionality is implemented now, except the arch-specific scenarios which need to be clarified in the follow-up [ticket](https://github.com/rpm-software-management/dnf5/issues/1487).
