### ISSUE TITLE
Bug fixes on dnf5daemon for GNOME Software

### ISSUE THREAD

**Issue by mcurlej** [rpm-software-management/dnf5#169]
We have several bugs filed in bugzilla which need to be resolved, before the work on a gnome plugin for dnf-daemon can be started. dnf-daemon does not uses package kit for interacting with the UI environments and libraries.

- [x] [Bug#2124503](https://bugzilla.redhat.com/show_bug.cgi?id=2124503) - dnf5daemon: API for offline upgrades
- [x] [Bug#2124304](https://bugzilla.redhat.com/show_bug.cgi?id=2124304) - dnf5 - server fails to run due to missing symbol
- [x] [Bug#2124468](https://bugzilla.redhat.com/show_bug.cgi?id=2124468) - [dnf5] Enhance list::upgrades
- [x] https://github.com/rpm-software-management/dnf5/issues/771
- [x] https://github.com/rpm-software-management/dnf5/issues/772
- [x] [Bug#2124525](https://bugzilla.redhat.com/show_bug.cgi?id=2124525) - [dnf5] Failed to load repo data
- [x] [Bug#2125181](https://bugzilla.redhat.com/show_bug.cgi?id=2125181) - [dnf5] Cannot install packages: 'g-io-error-quark: GDBus.Error:org.rpm.dnf.v0.Error: Not authorized (36)'
- [x] [Bug#2125232](https://bugzilla.redhat.com/show_bug.cgi?id=2125232) - [dnf5] Update dnf5/dnf5daemon-server/dbus/interfaces/*.xml files
- [x] [Bug 2184271](https://bugzilla.redhat.com/show_bug.cgi?id=2184271) - dnf5daemon-client crashed in __gnu_cxx::__verbose_terminate_handler() [clone .cold]() when upgrading kf5-filesystem
- [x] [Bug 2184276](https://bugzilla.redhat.com/show_bug.cgi?id=2184276) - [F38+copr] dnf5daemon-server crashes on fetching package indexes in _ZN22DownloadCallbacksProxy16add_new_downloadEPvPKcd
- [x] [Bug 2184277](https://bugzilla.redhat.com/show_bug.cgi?id=2184277) - [F38+copr] dnf5daemon-server crashes on installing package in _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC2ERKS4_
- [x] #451
- [x] https://github.com/rpm-software-management/dnf5/issues/1189

**Comment by m-blaha** [comment]
Yeah, I noticed them and I plan to investigate today.
As far as blockers are concerned - I'm not sure whether github supports such functionality. But I'm adding the bugs to the list in description.
