### ISSUE TITLE
DNF config-manager Plugin

### ISSUE THREAD

**Issue by j-mracek** [rpm-software-management/dnf5#405]
Documentation if dnf4 command - https://dnf-plugins-core.readthedocs.io/en/latest/config_manager.html

I am proposing to not keep DNF4 compatibility, because the syntax was not the best one and we also have new requirements due to support of drop-in directories for configuration.

- [x] Investigate options how to implement configuration overrides for main config
    - implemented in https://github.com/rpm-software-management/dnf5/pull/813
- [x] Investigate options how to implement configuration overrides for repositories
    - implemented in https://github.com/rpm-software-management/dnf5/pull/820
 - Implement mechanism to synchronize dnf and subscription-manager

- [ ] implement configuration management and repositories
    - Will be implemented in https://github.com/rpm-software-management/dnf5/pull/907
 - Configuration of repositories could be handled by a different command that for main repositories (under `repo` command)
 - missing feature in DNF4 - unable do dump repository configuration
     - Implementation of master configuration dump and repository configuration dump https://github.com/rpm-software-management/dnf5/pull/877. Unlike dnf4, it can be combined with any command - they are global dnf5 options, not part of config-manager. 
     - In addition, dump of variables are implemented. https://github.com/rpm-software-management/dnf5/pull/875. (missing in DNF4)
 - `--save` option was somehow strange in DNF4

Additional inspiration for handling of drop-in configuration:
https://github.com/rpm-software-management/libdnf/issues/1387
https://github.com/rpm-software-management/dnf/pull/1414

**Comment by ptoscano** [comment]
>     * [ ]  Investigate options how to implement configuration overrides for repositories
> 
>     * Implement mechanism to synchronize dnf and subscription-manager

I started a separate discussion about this, i.e. #422.

**Comment by inknos** [comment]
Issues reported by the lack of config-manager plugin here https://bodhi.fedoraproject.org/updates/FEDORA-2023-69dfac15db#comment-3063374

**Comment by msrb** [comment]
Fedora CI relies on the config-manager plugin as well:

```
Unknown argument "config-manager" for command "dnf5". Add "--help" for more information about the arguments.
```

**Comment by juhp** [comment]
Currently I use `dnf-3 config-manager` as a workaround in the meantime.

**Comment by msrb** [comment]
Thanks!

Is `dnf-3 config-manager` something we can expect to exist in Fedora 40+ (and later CentOS Stream, etc)? Or is it just a temporary workaround that might go away in the not so distant future?

**Comment by Andrei-Stepanov** [comment]
@j-mracek hello, could you please help us, 

```
Configuration of repositories could be handled by a different command that for main repositories (under repo command)
```

I checked this command. It cannot modify the repo: enable/disable. This command can only show info.

Automation is very important. Could you please give any ideas on how we can enable disable repos in an automated way (from bash script)?  

Thank you in advance.

**Comment by AdamWill** [comment]
@Andrei-Stepanov it's not very pretty, but this is how I'm doing it in openQA:

    sed -i -e "s,enabled=1,enabled=0,g" /etc/yum.repos.d/fedora-updates-testing.repo

replace with the appropriate repo file, of course.

**Comment by j-mracek** [comment]
Thank you @AdamWill for a workaround.

**Comment by praiskup** [comment]
Seems like closed by mistake;  shouldn't #907 close this one?

**Comment by j-mracek** [comment]
Thank you for notes

**Comment by bschaatsbergen** [comment]
Hey @jan-kolarik, 

It looks like some Fedora docs are still referencing the old `--add-repo` method for `dnf config-manager`. Since DNF5 broke backward compatibility and introduced `addrepo`, this pull request updates the Fedora documentation: https://pagure.io/fedora-docs/quick-docs/pull-request/783. 

Is this something you're able to look at? Thanks!

**Comment by Saarsk** [comment]
> I am proposing to not keep DNF4 compatibility, because the syntax was not the best one and we also have new requirements due to support of drop-in directories for configuration.

I guess that's fine, but I don't think this should prevent fixing the following problems:
- Non-descriptive and unhelpful output when inputting commands/instructions written pre-DNF5
- Command not being performed despite being available via `dnf-3`, 
`dnf4` or even `dnf` (**DNF5**). See below.

---

### A specific example:
A user follows [instructions for installing Brave Browser](https://brave.com/linux/#fedora-rockyrhel) which references `--add-repo`. This kind of stuff is inevitable to happen to users. The output with DNF5 is `Unknown argument "--add-repo" for command "config-manager". Add "--help" for more information about the arguments.`.


### Proposed solution of problem 1:
A better output would be to actually explain why it doesn't work. :slightly_smiling_face:  It's reasonable for the user to expect it to work, especially when the `dnf` command is the same (which it also should be).


### Proposed solution of problem 2:
Since it functionally does allegedly work can there be an alias put in place so that the many instructions that continues to exist can also continue to work and not become broken? Of course, along with a message like "Note: This is an outdated command option and implemention. It should be updated to comply with DNF5 specifications. Consider notifying the developer if this was part of the official instructions or documentation.`. The information also informs users that the provided instructions are outdated and should be updated (which may prompt them to relay this information to who(m)ever it may regard.

[This thread on fedoraprojects.org](https://discussion.fedoraproject.org/t/unknown-argument-config-manager-for-command-dnf5/85210) claims that **DNF5** lack the functionality so `dnf-3` has to be used with a modified command. 

[This thread](https://discussion.fedoraproject.org/t/how-to-add-repos-on-dnf5/131574/) suggests that it does indeed work on **DNF5** (with a modified command). The use of `dnf4` is also mentioned as a solution, which makes this all the more confusing, with the multiple solutions and conflicting information.

If using `dnf-3` or `dnf4` (I have no idea which is better or worse) can cause issues when **DNF5** is deployed, at least there should be a helpful output instead of "there was a problem". :slightly_smiling_face: And if it does work in **DNF5**, an alias or command translation would be very helpful and beneficial.

---

**Additional context to why this is arguably important:**
From time to time I'm sending commands or links to instructions to friends and family that are in a different country (even over the phone). Issues like this would most certainly be a considerable source of frustration and could unfortunately reflect poorly on the distribution or Linux (from a user's perspective, such problems can (and will) be associated with the OS). I became aware of the issue now trying to install the browser on a new system and it was not clear what was the issue and trying to figure out the best solution, free from caveats, wasn't easy. I'm still not sure which of the many suggested solutions is the best one. Especially since the mixing of **DNF5** and older implementations (`dnf-3`, `dnf4` etc.) have been adviced against for various reasons like ownership and potential inability to properly manage updates, apps and dependencies.

**Comment by bschaatsbergen** [comment]
FYI, I’ve updated the Fedora quick docs to include both DNF4 and DNF5. https://docs.fedoraproject.org/en-US/quick-docs/adding-or-removing-software-repositories-in-fedora/
