### ISSUE TITLE
DNF core commands - tracking issue

### ISSUE THREAD

**Issue by j-mracek** [rpm-software-management/dnf5#429]
- [ ] [alias](https://github.com/rpm-software-management/dnf5/issues/131)
- [ ] [autoremove](https://github.com/rpm-software-management/dnf5/issues/132)
- [ ] [check](https://github.com/rpm-software-management/dnf5/issues/133)
- [ ] [check-update](https://github.com/rpm-software-management/dnf5/issues/134)
- [x] [clean](https://github.com/rpm-software-management/dnf5/issues/135)
- [ ] deplist
- [ ] [distro-sync](https://github.com/rpm-software-management/dnf5/issues/136)
- [ ] [downgrade](https://github.com/rpm-software-management/dnf5/issues/137)
- [ ] [group](https://github.com/rpm-software-management/dnf5/issues/138)
- [ ] [help](https://github.com/rpm-software-management/dnf5/issues/139)
- [ ] [history](https://github.com/rpm-software-management/dnf5/issues/140)
- [x] [info](https://github.com/rpm-software-management/dnf5/issues/141)
- [ ] [install](https://github.com/rpm-software-management/dnf5/issues/142)
- [x] [list](https://github.com/rpm-software-management/dnf5/issues/143)
- [ ] [makecache](https://github.com/rpm-software-management/dnf5/issues/144)
- [ ] [mark](https://github.com/rpm-software-management/dnf5/issues/145)
- [ ] [module](https://github.com/rpm-software-management/dnf5/issues/146)
- [ ] [provides](https://github.com/rpm-software-management/dnf5/issues/147)
- [ ] [reinstall](https://github.com/rpm-software-management/dnf5/issues/148)
- [ ] [remove](https://github.com/rpm-software-management/dnf5/issues/149)
- [ ] [repoinfo](https://github.com/rpm-software-management/dnf5/issues/150)
- [ ] [repolist](https://github.com/rpm-software-management/dnf5/issues/151)
- [ ] [repoquery](https://github.com/rpm-software-management/dnf5/issues/122)
- [ ] repository-packages
- [x] [search](https://github.com/rpm-software-management/dnf5/issues/152)
- [ ] [shell](https://github.com/rpm-software-management/dnf5/issues/153)
- [ ] [swap](https://github.com/rpm-software-management/dnf5/issues/154)
- [ ] [updateinfo](https://github.com/rpm-software-management/dnf5/issues/155)
- [ ] [upgrade](https://github.com/rpm-software-management/dnf5/issues/156)
- [ ] [upgrade-minimal](https://github.com/rpm-software-management/dnf5/issues/157)
