### ISSUE TITLE
Update to 5.0.14 in Rawhide

### ISSUE THREAD

**Issue by jan-kolarik** [rpm-software-management/dnf5#635]
This is intended as a tracking issue about problems found related to dnf5 5.0.14 [bodhi update](https://bodhi.fedoraproject.org/updates/FEDORA-2023-69dfac15db) (switching to dnf5 as default package manager) in Rawhide.

There is a list of problems discovered so far:
- [x] missing `groupinstall` command
  - QA team mentioned that using `group install` workaround should be fine for them
  - document the change: https://github.com/rpm-software-management/dnf5/pull/663
- [x] missing `repo-pkgs` command
  - is it enough to use f.e. `dnf5 repoquery --repo brew-101869798` instead of the failing `yum repo-pkgs brew-101869798 list --showduplicates` ?
  - this is an error from bodhi report, f.e. [here](https://artifacts.dev.testing-farm.io/941a9685-7c22-4f03-ae56-83a48a85cd6e/)
- [x] missing `config-manager --set-disabled`
  - https://github.com/rpm-software-management/dnf5/issues/405
- [x] missing `reinstall --allowerasing`
  - not implemented yet for this command
  - fixing PR: https://github.com/rpm-software-management/dnf5/pull/637
- [x] missing `remove --noautoremove`
  - https://bugzilla.redhat.com/show_bug.cgi?id=2216622
  - replaced with the `clean_requirements_on_remove` configuration option
  - improved docs in PR: https://github.com/rpm-software-management/dnf5/pull/641
- [x] missing `repoquery --repofrompath`
  - https://github.com/rpm-software-management/dnf5/issues/549
  - needed for Rawhide production testing environment
- [x] missing `--cacheonly`
  - `fedora-review is breaking in Rawhide because dnf repoquery -C isn't implemented.`
  - https://github.com/rpm-software-management/dnf5/issues/227
- [x] missing command virtual provides, like `dnf install -y 'dnf-command(copr)'`
  - https://github.com/rpm-software-management/dnf5/issues/566
- [x] `install --skip-broken` not working as expected
  - https://bugzilla.redhat.com/show_bug.cgi?id=2216660
  - `skip_if_unavailable` was introduced
- [ ] `skip_if_unavailable=False` by default now
  - https://bugzilla.redhat.com/show_bug.cgi?id=2216205
  - document the change
- [x] copr plugin: need to explicitly define Rawhide chroot
  - before: `dnf copr enable repo_name`
  - now: `dnf copr enable repo_name fedora-rawhide-x86_64`
  - https://github.com/rpm-software-management/dnf5/issues/706
- [x] ownership problems
  - /var/lib/libdnf5 not owned - not used anymore, /usr/lib64/libdnf5 is owned by dnf5
  - /var/cache/libdnf5 not owned - should be already fixed in upstream
  - /etc/dnf not owned - owned by dnf-data which is required by dnf5
  - https://bugzilla.redhat.com/show_bug.cgi?id=2216849
- [x] builddep command not available by default
  - https://bugzilla.redhat.com/show_bug.cgi?id=2217933
  - https://pagure.io/fedora-kickstarts/pull-request/967
  - dnf5-plugins are now providing this command instead of the dnf-plugins-core
- [ ] man dnf not working
  - https://bugzilla.redhat.com/show_bug.cgi?id=2216850
- [x] not possible to upgrade to the newest dnf from older dnf
  - https://bugzilla.redhat.com/show_bug.cgi?id=2216807
  - from dnf-4.15.1-1 to dnf-4.16.1-2 in Rawhide
- [x] not possible to upgrade from `dnf5` ?
  - `Problem: The operation would result in removing the following protected packages: dnf`
  - upgrade from dnf is OK, upgrade from dnf5 returns the error above
  - probably due to handling of protected packages differently in dnf and dnf5 in some versions between - this is reproducible with dnf 4.15.1 and dnf5 5.0.11 in Rawhide
  - reproducible only having older dnf and dnf5 in specific versions

**Comment by mattiaverga** [comment]
I think another problem is that `$releasever` is expanded as `rawhide` instead of `39`.
Trying to enable the fedora-infra repository fails because the URL is expanded to `https://kojipkgs.fedoraproject.org/repos-dist/frawhide-infra/` instead of `https://kojipkgs.fedoraproject.org/repos-dist/f39-infra/`.

**Comment by m-blaha** [comment]
The releasever detection algorithm hasn't changed in dnf5 (there still can be a bug in implementation, though).
The releasever is determined by the version of `system-release(releasever)` provide (there are other fallbacks, but this has the highest priority):

```
# dnf repoquery --whatprovides 'system-release(releasever)'
fedora-release-common-0:39-0.14.noarch

# dnf repoquery --provides fedora-release-common | grep releasever
system-release(releasever) = rawhide
```

**Comment by mattiaverga** [comment]
Uh, I was wrong. I've started to see some automated tests failing with an error about dnf being unable to load a repository and I thought it was due to a different variable expansion.
The truth is that dnf just ignored the broken repository, while dnf5 doesn't ignore the error and causes the failure. For reference see https://github.com/fedora-infra/bodhi/actions/workflows/tests.yml

**Comment by juhp** [comment]
On the other hand, `dnf copr enable ...` requires mentioning rawhide chroot because dnf-5.0.15 is assumes the rawhide chroot is `fedora-39-x86_64` (not actual `fedora-rawhide-x86_64`).

**Comment by jan-kolarik** [comment]
All fixes related to the functionality of DNF5 itself discovered here should now be resolved. I've created [a follow-up issue](https://github.com/rpm-software-management/dnf5/issues/1057) for deployment-related things that are to be addressed during the planned future switch.
